// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const Map<String, String> _fallbackApiKeys = {
    'FIREBASE_API_KEY_ANDROID': 'AIzaSyAIbnovBWofy6gMFlG_lBHJ_Y2c6BR8nBk',
    'FIREBASE_API_KEY_IOS': 'AIzaSyAIbnovBWofy6gMFlG_lBHJ_Y2c6BR8nBk',
    'FIREBASE_API_KEY_MACOS': 'AIzaSyAIbnovBWofy6gMFlG_lBHJ_Y2c6BR8nBk',
    'FIREBASE_API_KEY_WEB': 'AIzaSyDJzfS6kvNWeglRInK3HyPPyRTQIEWDgA8',
    'FIREBASE_API_KEY_WINDOWS': 'AIzaSyDJzfS6kvNWeglRInK3HyPPyRTQIEWDgA8',
  };

  static String _requiredDefine(String name) {
    final value = String.fromEnvironment(
      name,
      defaultValue: _fallbackApiKeys[name] ?? '',
    );
    if (value.isEmpty) {
      throw StateError('Missing required --dart-define: $name');
    }
    return value;
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: _requiredDefine('FIREBASE_API_KEY_WEB'),
    appId: '1:1063758818542:web:696dbcf7db55ec66d317ff',
    messagingSenderId: '1063758818542',
    projectId: 'biostream-12',
    authDomain: 'biostream-12.firebaseapp.com',
    storageBucket: 'biostream-12.firebasestorage.app',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: _requiredDefine('FIREBASE_API_KEY_ANDROID'),
    appId: '1:1063758818542:android:99a2c2ef37f13eafd317ff',
    messagingSenderId: '1063758818542',
    projectId: 'biostream-12',
    storageBucket: 'biostream-12.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: _requiredDefine('FIREBASE_API_KEY_IOS'),
    appId: '1:1063758818542:ios:9c4e7938c602184bd317ff',
    messagingSenderId: '1063758818542',
    projectId: 'biostream-12',
    storageBucket: 'biostream-12.firebasestorage.app',
    iosBundleId: 'com.example.biostream',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: _requiredDefine('FIREBASE_API_KEY_MACOS'),
    appId: '1:1063758818542:ios:9c4e7938c602184bd317ff',
    messagingSenderId: '1063758818542',
    projectId: 'biostream-12',
    storageBucket: 'biostream-12.firebasestorage.app',
    iosBundleId: 'com.example.biostream',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: _requiredDefine('FIREBASE_API_KEY_WINDOWS'),
    appId: '1:1063758818542:web:d35c17ea956f559dd317ff',
    messagingSenderId: '1063758818542',
    projectId: 'biostream-12',
    authDomain: 'biostream-12.firebaseapp.com',
    storageBucket: 'biostream-12.firebasestorage.app',
  );
}
